project:
  type: website
  output-dir: docs

# Meta
description-meta: "Matías Deneken — actualizaciones y recursos en ciencia de datos sociales."
author-meta: "Matías Deneken"

website:
  title: "Matías Deneken"
  image: "/files/images/my-face.JPG"
  description: "Sociologist and Data Scientist | Research in Computational Social Science"
  navbar:
    background: light
    left:
      - text: Publications
        href: publications.qmd
      - text: Conferences
        href: conferences.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Experience
        href: experience.qmd
    right: 
      - text: CV
        href: files/nsf-biosketch.pdf
      - icon: github
        href: https://github.com/matdknu
        target: _blank
      - icon: envelope
        href: mailto:m.deneken@alumni.uc.cl
  
  page-navigation: true
  
  page-footer: 
    left: "[Matías Deneken](https://matdknu.github.io) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Actualizado en Quarto por Matías Deneken"
    right:  
      - icon: github
        href: https://github.com/matdknu
        target: _blank
      - text: "{{< fa brands bluesky >}}" 
        href: https://bsky.app
        target: _blank
      - icon: rss
        href: posts.xml
        target: _blank  
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/matdknu
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://matdknu.github.io"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

